facetapi.facet_source:
  type: config_object
  label : 'Facet'
  mapping:
    filter_key:
      type: string
      label: 'Filter key'
    overrides:
      type: sequence
      label: 'Overrides'
      sequence:
        type: mapping
        label: 'Override'
        mapping:
          filter_key:
            type: string
            label: 'Filter key'
